// @ts-check
// brand jsonb -> tokens.css (spec §6.4). A missing or malformed palette key is an
// error, never a silent default color (OHF §1 in CSS form).

export const PALETTE_KEYS = /** @type {const} */ (['bg', 'surface', 'fg', 'muted', 'line', 'accent', 'accent2', 'dark', 'black']);
export const SCHEMES = /** @type {const} */ (['dark-dominant', 'light']);
export const PRESETS = /** @type {const} */ (['coastal']);
const FALLBACK = Object.freeze({ display: "Georgia, 'Times New Roman', serif", body: 'system-ui, -apple-system, Segoe UI, sans-serif' });

const HEX = /^#[0-9a-fA-F]{6}$/;
const FONT = /^[A-Za-z0-9 ]{1,40}$/;
const RADIUS = /^\d{1,2}(\.\d+)?(px|rem)$/;
const ASSET = /^(\/sites\/[a-z0-9-]+\/[A-Za-z0-9._\/-]+|[0-9a-f-]{36})$/;

export class BrandError extends Error {
  /** @param {string[]} problems */
  constructor(problems) { super(`invalid brand: ${problems.join('; ')}`); this.problems = problems; }
}

/** @param {any} brand @returns {string[]} */
export function brandProblems(brand) {
  const p = [];
  if (!brand || typeof brand !== 'object') return ['brand must be an object'];
  if (!PRESETS.includes(brand.preset)) p.push(`preset must be one of ${PRESETS.join(', ')}`);
  if (!SCHEMES.includes(brand.scheme)) p.push(`scheme must be one of ${SCHEMES.join(', ')}`);
  const pal = brand.palette || {};
  for (const k of PALETTE_KEYS) {
    if (!(k in pal)) p.push(`palette.${k} is missing`);
    else if (!HEX.test(pal[k])) p.push(`palette.${k} must be #rrggbb, got ${JSON.stringify(pal[k])}`);
  }
  for (const k of Object.keys(pal)) if (!(/** @type {readonly string[]} */ (PALETTE_KEYS)).includes(k)) p.push(`palette.${k} is not a palette key`);
  for (const k of ['display', 'body']) {
    const v = brand.type && brand.type[k];
    if (!v || !FONT.test(v)) p.push(`type.${k} must be a font family name`);
  }
  if (!RADIUS.test(String(brand.radius || ''))) p.push('radius must look like 2px or 0.25rem');
  for (const k of ['logo', 'favicon', 'ogImage']) {
    if (brand[k] != null && !ASSET.test(String(brand[k]))) p.push(`${k} must be a /sites/<slug>/ path or a media id`);
  }
  return p;
}

/** @param {any} brand */
export function validateBrand(brand) {
  const p = brandProblems(brand);
  if (p.length) throw new BrandError(p);
  return brand;
}

/** @param {string} family @param {'display'|'body'} role */
const stack = (family, role) => `'${family}', ${FALLBACK[role]}`;

/** Google Fonts stylesheet href for the brand's type pairing. @param {any} brand */
export function fontsHref(brand) {
  validateBrand(brand);
  const fam = (/** @type {string} */ f, /** @type {string} */ axes) => `family=${encodeURIComponent(f).replace(/%20/g, '+')}${axes}`;
  return `https://fonts.googleapis.com/css2?${fam(brand.type.display, ':ital,wght@0,400;0,500;0,600;1,400')}&${fam(brand.type.body, ':wght@400;500;600')}&display=swap`;
}

/**
 * Brand-agnostic admin neutrals (mockup "ADMIN TOKENS"). The same for every
 * tenant; only --a-accent follows the brand. Emitted here so admin/** carries
 * no color literals at all (static guard 3).
 */
export const ADMIN_TOKENS = Object.freeze({
  'a-bg': '#f6f7f8', 'a-fg': '#1b2024', 'a-mute': '#5f6b74', 'a-line': '#dce1e5', 'a-surface': '#ffffff',
  'a-ok': '#2f855a', 'a-ok-bg': '#e6f4ec', 'a-warn': '#b7791f', 'a-warn-bg': '#fff6e5',
  'a-bad': '#c53030', 'a-bad-bg': '#fbeaea', 'a-on-fg': '#ffffff', 'a-radius': '6px',
});

/** @param {any} brand @returns {string} */
export function tokensCss(brand) {
  validateBrand(brand);
  const pal = brand.palette;
  const decl = PALETTE_KEYS.map((k) => `--t-${k === 'accent2' ? 'accent-2' : k}:${pal[k].toLowerCase()};`).join('');
  const field = brand.scheme === 'dark-dominant' ? 'var(--t-dark)' : 'var(--t-bg)';
  const onField = brand.scheme === 'dark-dominant' ? 'var(--t-bg)' : 'var(--t-fg)';
  const admin = Object.entries(ADMIN_TOKENS).map(([k, v]) => `--${k}:${v};`).join('') + '--a-accent:var(--t-accent);';
  const base = `${decl}${admin}--t-field:${field};--t-on-field:${onField};--t-display:${stack(brand.type.display, 'display')};--t-body:${stack(brand.type.body, 'body')};--t-radius:${brand.radius};`;
  // Dark mode: the page field and text invert; the dark brand colors carry the surfaces.
  const dark = `--t-bg:${pal.black.toLowerCase()};--t-surface:${pal.dark.toLowerCase()};--t-fg:${pal.bg.toLowerCase()};--t-muted:${pal.accent2.toLowerCase()};--t-line:color-mix(in srgb, ${pal.accent2.toLowerCase()} 35%, transparent);`;
  return [
    `/* generated by renderer/tokens.js — do not edit */`,
    `:root{${base}}`,
    `@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){${dark}}}`,
    `:root[data-theme="dark"]{${dark}}`,
    '',
  ].join('\n');
}
