// Dev/CI only: writes .dev-stack/env with a random JWT secret and the anon and
// service keys signed with it. Never used for a hosted project, whose keys come
// from the Supabase dashboard.
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { signJwt } from '../../lib/jwt.js';
import { ENV_KEYS as K } from '../../lib/db.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const dir = join(root, '.dev-stack');
const file = join(dir, 'env');
mkdirSync(dir, { recursive: true });

const port = (k, d) => process.env[k] || d;
const PG = port('DEV_PG_PORT', '54322');
const GW = port('DEV_GATEWAY_PORT', '54321');

let secret;
if (existsSync(file)) {
  const m = new RegExp(`^${K.jwtSecret}=(.+)$`, 'm').exec(readFileSync(file, 'utf8'));
  if (m) secret = m[1];
}
secret ||= randomBytes(32).toString('hex');

const iat = Math.floor(Date.now() / 1000);
const exp = iat + 10 * 365 * 24 * 3600;
const anon = await signJwt({ role: 'anon', iss: 'supabase-dev', iat, exp }, secret);
const service = await signJwt({ role: 'service_role', iss: 'supabase-dev', iat, exp }, secret);

writeFileSync(file, [
  '# generated by scripts/dev-stack/keys.js — dev/CI only',
  'NODE_ENV=development',
  'PORT=3000',
  `${K.dbUrl}=postgres://postgres@127.0.0.1:${PG}/postgres`,
  `${K.url}=http://localhost:${GW}`,
  `${K.anonKey}=${anon}`,
  `${K.serviceKey}=${service}`,
  `${K.jwtSecret}=${secret}`,
  'TS_DEFAULT_HOST=localhost',
  'TS_PUBLIC_BASE_SCHEME=http',
  '',
].join('\n'));
console.log(`wrote ${file}`);
